In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.6


##### **Python basics - list**

In [3]:
ls = [1, 2, 3]
arr_from_list = np.array(ls)

In [4]:
arr_from_list

array([1, 2, 3])

In [5]:
arr = np.array([1, 2, 3, 4])

print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
x = np.arange(10).reshape((5, 2))

In [7]:
y = x.reshape((2,5))

In [9]:
x, y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

List indexing

In [35]:
l1 = [1, 2, 3, 4]

l1[:2], l1[2:], l1[1:3]

([1, 2], [3, 4], [2, 3])

The entire list without the last element

In [37]:
l1[:-1]

[1, 2, 3]

Reversing the list

In [38]:
l1[::-1]

[4, 3, 2, 1]

Step in indexing

In [39]:
l1[::2]

[1, 3]

List that contains an element of the different datatype.

In [1]:
l1 = [1, 2.4, 3j]

for el in l1:
    print(f"Type of {el}: {type(el)}")

Type of 1: <class 'int'>
Type of 2.4: <class 'float'>
Type of 3j: <class 'complex'>


Duplication of the list by multiplication - **shallow copy**.

In [8]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [11]:
l2 = [1] * 5
l2

[1, 1, 1, 1, 1]

In [12]:
l2[0] += 20
l2

[21, 1, 1, 1, 1]

In [15]:
l3 = [[]] * 3
l3

[[], [], []]

In [16]:
l3[0].append(10)
l3

[[10], [10], [10]]

Iterating through a list.

In [22]:
l4 = [1, 2, 3, 4] 

for x in l4:
    print(x, end=" ")

1 2 3 4 

In [29]:
for index, element in enumerate(l4):
    print(f"{index} -> {element}")

0 -> 1
1 -> 2
2 -> 3
3 -> 4


In [28]:
l5 = np.array([[[1, 2], [3, 4]]])

for x in np.nditer(l5):
    print(x, end=" ")

1 2 3 4 

Iterator example.

In [31]:
a = ["apple", "juice"]

itr = iter(a)

In [32]:
next(itr)

'apple'

List comprehension.

In [33]:
lc = [i**2 for i in range(10)]
lc

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

##### **Numpy**

np.ndarray - n-dimensional array

Creating arrays

In [40]:
x = np.array([1, 2, 3])

x, len(x), x[0]

(array([1, 2, 3]), 3, 1)

In [41]:
3 in x

True

In [43]:
y = np.array([[1, 2], [1, 2]])

y, len(y), y[0]

(array([[1, 2],
        [1, 2]]),
 2,
 array([1, 2]))

In [44]:
# data type and number of dimensions
y.dtype, y.ndim

(dtype('int32'), 2)

Ways to create a numpy array

In [47]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.arange(27).reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
np.full((3, 4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [59]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.linspace(0, 4)

array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
       0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
       0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
       1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
       1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
       2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
       2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
       2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
       3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
       3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ])

In [63]:
np.linspace(0, 4, 4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [64]:
np.tile(np.array([1, 2]), 5)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [65]:
np.array([1, 2, 3]).repeat(2)

array([1, 1, 2, 2, 3, 3])

In [66]:
np.random.rand(10)

array([0.02964236, 0.05271696, 0.82824895, 0.45352199, 0.7078005 ,
       0.02437403, 0.81195197, 0.45948673, 0.67896448, 0.59063261])

Array's type

In [4]:
x = np.float64(1.0)
x

1.0

In [5]:
y = np.array([1, 2, 3], dtype="f")
y

array([1., 2., 3.], dtype=float32)

In [6]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [8]:
np.zeros(3), np.zeros(3, dtype=np.uint8), np.zeros(3, dtype=np.float64), np.zeros(3, dtype=bool)

(array([0., 0., 0.]),
 array([0, 0, 0], dtype=uint8),
 array([0., 0., 0.]),
 array([False, False, False]))

Special values defined in numpy: nan, inf

In [9]:
np_inf = np.inf

In [11]:
np_inf, -np_inf, np_inf + 1, np_inf * 3, np_inf * 0, np_inf - np_inf

(inf, -inf, inf, inf, nan, nan)

In [12]:
type(np_inf)

float

In [13]:
-0.0

-0.0

Special numpy function to compare nan

In [14]:
np.nan == np.nan

False

In [15]:
np.isnan(np.nan)

True

Array with text

In [17]:
text_array = np.array(["some", "text"])
text_array

array(['some', 'text'], dtype='<U4')

In [19]:
text_array[0], text_array[-1]

('some', 'text')

In [21]:
text_array_twice = np.array(["some", "text"] * 2)
text_array_twice

array(['some', 'text', 'some', 'text'], dtype='<U4')

In [26]:
text_array_twice.itemsize, text_array_twice.size

(16, 4)

#### **Array operation**

In [40]:
x = np.arange(10)
y = np.array([1, 2, 3, 4])
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4]))

In [30]:
x.itemsize, x.size

(4, 10)

In [31]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [33]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [50]:
x = x[0:4]

x * y, x + y, x - y, x / y, x ** y, x % y

(array([ 0,  2,  6, 12]),
 array([1, 3, 5, 7]),
 array([-1, -1, -1, -1]),
 array([0.        , 0.5       , 0.66666667, 0.75      ]),
 array([ 0,  1,  8, 81], dtype=int32),
 array([0, 1, 2, 3], dtype=int32))

#### **Logical operations**

In [51]:
x

array([0, 1, 2, 3])

In [52]:
x > 1

array([False, False,  True,  True])

In [53]:
x != 2

array([ True,  True, False,  True])

In [54]:
x == 2

array([False, False,  True, False])

In [57]:
temp_val1 = (x > 1) & (x < 3)
temp_val2 = ~temp_val1

temp_val1, temp_val2

(array([False, False,  True, False]), array([ True,  True, False,  True]))

In [58]:
temp_val1 | temp_val2

array([ True,  True,  True,  True])

#### **Matrix operations**

In [59]:
x, y

(array([0, 1, 2, 3]), array([1, 2, 3, 4]))

Element-by-element multiplication:

In [60]:
x * y

array([ 0,  2,  6, 12])

Scalar product

In [65]:
x @ y

20

In [66]:
x @ y == (x * y).sum()

True

In [67]:
np.dot(x, y)

20

In [68]:
np.matmul(x, y)

20