In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.6


1. **Numpy array and Python lists**

In [3]:
ls = [1, 2, 3]
arr_from_list = np.array(ls)

In [4]:
arr_from_list

array([1, 2, 3])

In [5]:
arr = np.array([1, 2, 3, 4])

print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
x = np.arange(10).reshape((5, 2))

In [7]:
y = x.reshape((2,5))

In [9]:
x, y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

Numpy array that contains an element of the different datatype.