In [38]:
import copy
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
df = pd.read_csv("../data/03/housing/housing_train.csv")
df

CRIM    ZN  INDUS  CHAS   NOX     RM   AGE     DIS  RAD    TAX  \
0     0.13960   0.0   8.56   0.0   NaN  6.167  90.0  2.4210    5  384.0   
1     0.03510  95.0   2.68   0.0   NaN  7.853  33.2  5.1180    4  224.0   
2    15.87440   0.0  18.10   0.0   NaN  6.545  99.1  1.5192   24  666.0   
3     0.18337   0.0  27.74   0.0   NaN  5.414  98.3  1.7554    4  711.0   
4     0.12816  12.5   6.07   0.0   NaN  5.885  33.0  6.4980    4  345.0   
..        ...   ...    ...   ...   ...    ...   ...     ...  ...    ...   
425   0.17120   0.0   8.56   0.0   NaN  5.836  91.9  2.2110    5  384.0   
426   0.29916  20.0   6.96   0.0   NaN  5.856  42.1  4.4290    3  223.0   
427   0.01501  80.0   2.01   0.0   NaN  6.635  29.7  8.3440    4  280.0   
428  11.16040   0.0  18.10   0.0  0.74  6.629  94.6  2.1247   24  666.0   
429   0.22876   0.0   8.56   0.0   NaN  6.405  85.4  2.7147    5  384.0   

     PTRATIO       B  LSTAT        MEDV  
0        NaN  392.69    NaN   86.066034  
1        NaN  392.78    NaN  207.700057  
2        NaN  396.90  21.08   46.689349  
3        NaN  344.05  23.97   29.980669  
4        NaN  396.90    NaN   89.461275  
..       ...     ...    ...         ...  
425     20.9  395.67  18.66   83.647456  
426     18.6  388.65    NaN   90.409128  
427     17.0  390.94    NaN  104.921869  
428     20.2  109.85  23.27   57.427501  
429     20.9   70.80    NaN   79.627685  

[430 rows x 14 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     430 non-null    float64
 1   ZN       430 non-null    float64
 2   INDUS    430 non-null    float64
 3   CHAS     408 non-null    float64
 4   NOX      52 non-null     float64
 5   RM       430 non-null    float64
 6   AGE      430 non-null    float64
 7   DIS      430 non-null    float64
 8   RAD      430 non-null    int64  
 9   TAX      420 non-null    float64
 10  PTRATIO  420 non-null    float64
 11  B        430 non-null    float64
 12  LSTAT    88 non-null     float64
 13  MEDV     430 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 47.2 KB


In [19]:
df["NOX"] = df.NOX.isnull().astype("int")

In [20]:
df["LSTAT"] = df.LSTAT.isnull().astype("int")

In [21]:
df

CRIM    ZN  INDUS  CHAS  NOX     RM   AGE     DIS  RAD    TAX  \
0     0.13960   0.0   8.56   0.0    1  6.167  90.0  2.4210    5  384.0   
1     0.03510  95.0   2.68   0.0    1  7.853  33.2  5.1180    4  224.0   
2    15.87440   0.0  18.10   0.0    1  6.545  99.1  1.5192   24  666.0   
3     0.18337   0.0  27.74   0.0    1  5.414  98.3  1.7554    4  711.0   
4     0.12816  12.5   6.07   0.0    1  5.885  33.0  6.4980    4  345.0   
..        ...   ...    ...   ...  ...    ...   ...     ...  ...    ...   
425   0.17120   0.0   8.56   0.0    1  5.836  91.9  2.2110    5  384.0   
426   0.29916  20.0   6.96   0.0    1  5.856  42.1  4.4290    3  223.0   
427   0.01501  80.0   2.01   0.0    1  6.635  29.7  8.3440    4  280.0   
428  11.16040   0.0  18.10   0.0    0  6.629  94.6  2.1247   24  666.0   
429   0.22876   0.0   8.56   0.0    1  6.405  85.4  2.7147    5  384.0   

     PTRATIO       B  LSTAT        MEDV  
0        NaN  392.69      1   86.066034  
1        NaN  392.78      1  207.700057  
2        NaN  396.90      0   46.689349  
3        NaN  344.05      0   29.980669  
4        NaN  396.90      1   89.461275  
..       ...     ...    ...         ...  
425     20.9  395.67      0   83.647456  
426     18.6  388.65      1   90.409128  
427     17.0  390.94      1  104.921869  
428     20.2  109.85      0   57.427501  
429     20.9   70.80      1   79.627685  

[430 rows x 14 columns]

In [22]:
X_train = df.drop(columns=['MEDV'])
y_train = df['MEDV']

In [23]:
X_train

CRIM    ZN  INDUS  CHAS  NOX     RM   AGE     DIS  RAD    TAX  \
0     0.13960   0.0   8.56   0.0    1  6.167  90.0  2.4210    5  384.0   
1     0.03510  95.0   2.68   0.0    1  7.853  33.2  5.1180    4  224.0   
2    15.87440   0.0  18.10   0.0    1  6.545  99.1  1.5192   24  666.0   
3     0.18337   0.0  27.74   0.0    1  5.414  98.3  1.7554    4  711.0   
4     0.12816  12.5   6.07   0.0    1  5.885  33.0  6.4980    4  345.0   
..        ...   ...    ...   ...  ...    ...   ...     ...  ...    ...   
425   0.17120   0.0   8.56   0.0    1  5.836  91.9  2.2110    5  384.0   
426   0.29916  20.0   6.96   0.0    1  5.856  42.1  4.4290    3  223.0   
427   0.01501  80.0   2.01   0.0    1  6.635  29.7  8.3440    4  280.0   
428  11.16040   0.0  18.10   0.0    0  6.629  94.6  2.1247   24  666.0   
429   0.22876   0.0   8.56   0.0    1  6.405  85.4  2.7147    5  384.0   

     PTRATIO       B  LSTAT  
0        NaN  392.69      1  
1        NaN  392.78      1  
2        NaN  396.90      0  
3        NaN  344.05      0  
4        NaN  396.90      1  
..       ...     ...    ...  
425     20.9  395.67      0  
426     18.6  388.65      1  
427     17.0  390.94      1  
428     20.2  109.85      0  
429     20.9   70.80      1  

[430 rows x 13 columns]

In [24]:
imputer = SimpleImputer(strategy="median")

In [25]:
X_train = imputer.fit_transform(X_train)    

In [26]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred = model.predict(X_train)

In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
y_pred = model.predict(X_train)

print("Model on all variables without NA")
print(f"Model MSE: {mean_squared_error(y_train, y_pred)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_train, y_pred))}")
print(f"Model MAE: {mean_absolute_error(y_train, y_pred)}")

Model on all variables without NA
Model MSE: 499.19463813910164
Model RMSE: 22.34266407882242
Model MAE: 15.329853228913283


In [33]:
obs = pd.DataFrame({
    'CRIM': [3.69],
    'ZN': [11.37],
    'INDUS': [11.15],
    'CHAS': [0.07],
    'NOX': [0],
    'RM': [6.29],
    'AGE': [68.91],
    'DIS': [3.77],
    'RAD': [9.50],
    'TAX': [410.95],
    'PTRATIO': [18.37],
    'B': [354.47],
    'LSTAT': [0],
})
obs

CRIM     ZN  INDUS  CHAS  NOX    RM    AGE   DIS  RAD     TAX  PTRATIO  \
0  3.69  11.37  11.15  0.07    0  6.29  68.91  3.77  9.5  410.95    18.37   

        B  LSTAT  
0  354.47      0

In [34]:
pred1 = model.predict(obs)

C:\Users\Kasia\anaconda3\envs\daftacademy-ds\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [35]:
pred1

array([62.14446917])

## Dla powyższego modelu, o ile wzrośnie predykcja ceny mieszkania jeżeli wartość w kolumnie RM zwiększymy o 2?

In [39]:
obs2 = copy.deepcopy(obs)

In [40]:
obs2["RM"] += 2

In [41]:
pred2 = model.predict(obs)

C:\Users\Kasia\anaconda3\envs\daftacademy-ds\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [43]:
pred2

array([112.70552289])

In [45]:
pred2 - pred1

array([50.56105372])